[build]
  command = "npm run build"
  publish = "dist"

# Admin routes
[[redirects]]
  from = "/admin/*"
  to = "/admin/index.html"
  status = 200

# Netlify Identity
[[redirects]]
  from = "/.netlify/identity/*"
  to = "/.netlify/identity/*"
  status = 200

# Handle client-side routing for the main site
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true

# Fallback for all other routes (SPA routing)
[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404